[package]
authors.workspace = true
description = "Pallet that announces each era's validator set to other system chains."
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "pallet-validator-set-announcer"
repository.workspace = true
version = "0.1.0"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-validator-collators = { workspace = true }
sp-runtime = { workspace = true }
sp-staking = { workspace = true }

frame-benchmarking = { optional = true, workspace = true }

[dev-dependencies]
pallet-session = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-session/runtime-benchmarks",
	"pallet-validator-collators/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-validator-collators/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-session/try-runtime",
	"pallet-validator-collators/try-runtime",
	"sp-runtime/try-runtime",
]
