[relaychain]
default_command = "/home/gab/polkadot-sdk/target/release/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
# args = ["-lpov_creation=debug"]

[[relaychain.nodes]]
name = "bob"
validator = true
# args = ["-lpov_creation=debug --execution native"]
# args = ["-lparachain=debug,parachain::pvf=debug,parachain::candidate-validation=debug"]

[[parachains]]
id = 2000
cumulus_based = true
chain = "asset-hub-rococo-local"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
command = "/home/gab/polkadot-sdk/target/release/polkadot-parachain"
args = ["--force-authoring --database nomt"]
# args = ["--force-authoring --database nomt --export-pov-to-path ~/polkadot-sdk/povs"]
