(function() {var implementors = {
"asset_hub_rococo_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"asset_hub_rococo_runtime/struct.Runtime.html\" title=\"struct asset_hub_rococo_runtime::Runtime\">Runtime</a>"]],
"asset_hub_westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"asset_hub_westend_runtime/struct.Runtime.html\" title=\"struct asset_hub_westend_runtime::Runtime\">Runtime</a>"]],
"bridge_hub_rococo_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"bridge_hub_rococo_runtime/struct.Runtime.html\" title=\"struct bridge_hub_rococo_runtime::Runtime\">Runtime</a>"]],
"bridge_hub_westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"bridge_hub_westend_runtime/struct.Runtime.html\" title=\"struct bridge_hub_westend_runtime::Runtime\">Runtime</a>"]],
"collectives_westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"collectives_westend_runtime/struct.Runtime.html\" title=\"struct collectives_westend_runtime::Runtime\">Runtime</a>"]],
"contracts_rococo_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"contracts_rococo_runtime/struct.Runtime.html\" title=\"struct contracts_rococo_runtime::Runtime\">Runtime</a>"]],
"coretime_rococo_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"coretime_rococo_runtime/struct.Runtime.html\" title=\"struct coretime_rococo_runtime::Runtime\">Runtime</a>"]],
"coretime_westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"coretime_westend_runtime/struct.Runtime.html\" title=\"struct coretime_westend_runtime::Runtime\">Runtime</a>"]],
"glutton_westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"glutton_westend_runtime/struct.Runtime.html\" title=\"struct glutton_westend_runtime::Runtime\">Runtime</a>"]],
"kitchensink_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"kitchensink_runtime/struct.Runtime.html\" title=\"struct kitchensink_runtime::Runtime\">Runtime</a>"]],
"parachain_template_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"parachain_template_runtime/struct.Runtime.html\" title=\"struct parachain_template_runtime::Runtime\">Runtime</a>"]],
"penpal_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"penpal_runtime/struct.Runtime.html\" title=\"struct penpal_runtime::Runtime\">Runtime</a>"]],
"people_rococo_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"people_rococo_runtime/struct.Runtime.html\" title=\"struct people_rococo_runtime::Runtime\">Runtime</a>"]],
"people_westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"people_westend_runtime/struct.Runtime.html\" title=\"struct people_westend_runtime::Runtime\">Runtime</a>"]],
"rococo_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"rococo_runtime/struct.Runtime.html\" title=\"struct rococo_runtime::Runtime\">Runtime</a>"]],
"solochain_template_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"solochain_template_runtime/struct.Runtime.html\" title=\"struct solochain_template_runtime::Runtime\">Runtime</a>"]],
"westend_runtime":[["impl <a class=\"trait\" href=\"frame_system_benchmarking/trait.Config.html\" title=\"trait frame_system_benchmarking::Config\">Config</a> for <a class=\"struct\" href=\"westend_runtime/struct.Runtime.html\" title=\"struct westend_runtime::Runtime\">Runtime</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()