[package]
name = "sp-state-machine-fuzz"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzzer for sp-state-machine storage append operations."
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "fuzz_append"
path = "src/fuzz_append.rs"

[dependencies]
ziggy = { workspace = true }
arbitrary = { workspace = true, features = ["derive"] }

sp-runtime = { workspace = true, default-features = true }
sp-state-machine = { features = ["fuzzing"], workspace = true, default-features = true }
