FROM rust AS builder

RUN apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get install -y \
		protobuf-compiler \
		clang libclang-dev

WORKDIR /polkadot
COPY . /polkadot
RUN rustup component add rust-src
RUN cargo build --locked --release -p pallet-revive-eth-rpc --bin eth-rpc

FROM docker.io/parity/base-bin:latest
COPY --from=builder /polkadot/target/release/eth-rpc /usr/local/bin/eth-rpc

USER root
RUN useradd -m -u 1001 -U -s /bin/sh -d /polkadot polkadot && \
# unclutter and minimize the attack surface
	rm -rf /usr/bin /usr/sbin && \
# check if executable works in this container
	/usr/local/bin/eth-rpc --help

USER polkadot

ENTRYPOINT ["/usr/local/bin/eth-rpc"]

CMD ["--dev"]
