[package]
name = "sp-virtualization"
version = "1.0.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
description = "Spawn a new polkavm instance from within the runtime/pvf"

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = false, features = ["bytes"] }
log = { workspace = true }
num_enum = { workspace = true, default-features = false }
polkavm = { workspace = true }
sp-crypto-hashing = { workspace = true, optional = true }
sp-externalities = { workspace = true, default-features = false }
sp-runtime-interface = { workspace = true, default-features = false }
sp-storage = { workspace = true, optional = true }
strum = { features = ["derive"], workspace = true }

[dev-dependencies]
sp-io = { workspace = true, default-features = true }
sp-tracing = { workspace = true }
sp-virtualization-test-fixture = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"num_enum/std",
	"polkavm/std",
	"sp-crypto-hashing/std",
	"sp-externalities/std",
	"sp-runtime-interface/std",
	"sp-storage/std",
	"sp-tracing/std",
	"strum/std",
]
