{
 "title": "Rococo BEEFY",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Rococo Beefy Best block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "substrate_beefy_best_block{chain=\"rococo_v2_2\", node=~\"rococo.*(validator|rpc).*\"}"
    }
   ]
  },
  {
   "title": "Rococo BEEFY Lagging Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "substrate_beefy_lagging_sessions{chain=\"rococo_v2_2\", node=~\"rococo.*(validator|3-rpc).*\"}"
    }
   ]
  },
  {
   "title": "Rococo BEEFY Validator Set ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "substrate_beefy_validator_set_id{chain=\"rococo_v2_2\", node=~\"rococo.*(validator|3-rpc).*\"}"
    }
   ]
  }
 ]
}