{
 "title": "BridgeHubWestend to BridgeHubRococo (00000002)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Best finalized Westend headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Westend_to_BridgeHubRococo_Sync_best_source_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At Westend"
    },
    {
     "expr": "Westend_to_BridgeHubRococo_Sync_best_source_at_target_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At BridgeHubRococo"
    }
   ]
  },
  {
   "title": "Best finalized Rococo headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "Rococo_to_BridgeHubWestend_Sync_best_source_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At Rococo"
    },
    {
     "expr": "Rococo_to_BridgeHubWestend_Sync_best_source_at_target_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At WestendBridgeHub"
    }
   ]
  },
  {
   "title": "Best finalized WestendBridgeHub headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_best_source_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At WestendBridgeHub"
    },
    {
     "expr": "BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_best_source_at_target_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At RococoBridgeHub"
    }
   ]
  },
  {
   "title": "Best finalized RococoBridgeHub headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_best_target_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At RococoBridgeHub"
    },
    {
     "expr": "BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_best_target_at_source_block_number{domain=\"parity-testnet\"}",
     "legendFormat": "At WestendBridgeHub"
    }
   ]
  },
  {
   "title": "Delivery race (00000002)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(label_replace(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=~\"source_latest_generated|target_latest_received\"}, \"type\", \"Latest message sent from BridgeHubWestend\", \"type\", \"source_latest_generated\"), \"type\", \"Latest BridgeHubWestend message received by BridgeHubRococo\", \"type\", \"target_latest_received\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Confirmations race (00000002)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(label_replace(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=~\"source_latest_confirmed|target_latest_received\"}, \"type\", \"Latest delivery confirmation from BridgeHubRococo to BridgeHubWestend\", \"type\", \"source_latest_confirmed\"), \"type\", \"Latest BridgeHubWestend message received by BridgeHubRococo\", \"type\", \"target_latest_received\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Delivery race lags (00000002)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "scalar(max_over_time(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=\"source_latest_generated\"}[2m]) OR on() vector(0)) - scalar(max_over_time(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=\"target_latest_received\"}[2m]) OR on() vector(0))",
     "legendFormat": "Undelivered messages"
    }
   ]
  },
  {
   "title": "Confirmations race lags (00000002)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "scalar(max_over_time(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=\"target_latest_received\"}[2m]) OR on() vector(0)) - scalar(max_over_time(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=\"source_latest_confirmed\"}[2m]) OR on() vector(0))",
     "legendFormat": "Unconfirmed messages"
    }
   ]
  },
  {
   "title": "Reward lags (00000002)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "scalar(max_over_time(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=\"source_latest_confirmed\"}[2m]) OR on() vector(0)) - scalar(max_over_time(BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_lane_state_nonces{domain=\"parity-testnet\",type=\"target_latest_confirmed\"}[2m]) OR on() vector(0))",
     "legendFormat": "Unconfirmed rewards"
    }
   ]
  }
 ]
}