{
 "title": "BridgeHubRococo <> BridgeHubWestend maintenance (00000002)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Relay build commit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_relay_build_info{domain=\"parity-testnet\"}",
     "legendFormat": "{{commit}}"
    }
   ]
  },
  {
   "title": "Relay build version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_relay_build_info{domain=\"parity-testnet\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Is relay running?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{domain=\"parity-testnet\",container=\"bridges-common-relay\"}",
     "legendFormat": "Is relay running"
    }
   ]
  },
  {
   "title": "Is relay running? (for alert)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "up{domain=\"parity-testnet\",container=\"bridges-common-relay\"}",
     "legendFormat": "Is relay running"
    }
   ]
  },
  {
   "title": "Relay errors/warnings per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count_over_time({container=\"bridges-common-relay\"} |~ `(?i)(warn|error|fail)` [1m])",
     "legendFormat": "Errors per minute"
    }
   ]
  },
  {
   "title": "Rococo headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "Rococo_to_BridgeHubWestend_Sync_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWestend doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "Westend headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "Westend_to_BridgeHubRococo_Sync_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWestend doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "BridgeHubRococo headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "BridgeHubRococo_to_BridgeHubWestend_MessageLane_00000002_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWestend doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "BridgeHubWestend headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "BridgeHubWestend_to_BridgeHubRococo_MessageLane_00000002_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWestend doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "Relay balances at RococoBridgeHub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "at_BridgeHubRococo_relay_BridgeHubWestendMessages_balance{domain=\"parity-testnet\"}",
     "legendFormat": "Messages Relay Balance"
    },
    {
     "expr": "at_BridgeHubRococo_relay_WestendHeaders_reward_for_msgs_to_BridgeHubWestend_on_lane_00000002{domain=\"parity-testnet\"} + at_BridgeHubRococo_relay_BridgeHubWestendMessages_reward_for_msgs_to_BridgeHubWestend_on_lane_00000002{domain=\"parity-testnet\"}",
     "legendFormat": "Pending reward"
    }
   ]
  },
  {
   "title": "Relay balances at WestendBridgeHub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "at_BridgeHubWestend_relay_BridgeHubRococoMessages_balance{domain=\"parity-testnet\"}",
     "legendFormat": "Messages Relay Balance"
    },
    {
     "expr": "at_BridgeHubRococo_relay_BridgeHubWestendMessages_reward_for_msgs_from_BridgeHubWestend_on_lane_00000002{domain=\"parity-testnet\"} + at_BridgeHubRococo_relay_BridgeHubWestendMessages_reward_for_msgs_to_BridgeHubWestend_on_lane_00000002{domain=\"parity-testnet\"}",
     "legendFormat": "Pending reward"
    }
   ]
  }
 ]
}