[package]
name = "sp-core-fuzz"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzzer for sp-core address URI parsing."
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "fuzz_address_uri"
path = "src/fuzz_address_uri.rs"

[dependencies]
ziggy = { workspace = true }
regex = { workspace = true }
sp-core = { workspace = true, default-features = true }
