flowchart
    parity[paritytech.github.io] --> devhub[polkadot_sdk_docs]

    devhub --> polkadot_sdk
    devhub --> reference_docs
    devhub --> guides
	devhub --> external_resources

    polkadot_sdk --> substrate
    polkadot_sdk --> frame
    polkadot_sdk --> xcm
	polkadot_sdk --> templates
