flowchart LR
	subgraph Parachain[A Polkadot Parachain]
		ParachainNode[Parachain Node]
		ParachainRuntime[Parachain Runtime]
	end

    FRAME -.-> ParachainRuntime
    Substrate[Substrate Node Libraries] -.-> ParachainNode

    CumulusC[Cumulus Node Libraries] -.-> ParachainNode
    CumulusR[Cumulus Runtime Libraries] -.-> ParachainRuntime
