flowchart LR
	subgraph Parachain[A Polkadot Parachain]
		ParachainClient[Parachain Client]
		ParachainRuntime[Parachain Runtime]
	end

    FRAME -.-> ParachainRuntime
    Substrate[Substrate Client Libraries] -.-> ParachainClient

    CumulusC[Cumulus Client Libraries] -.-> ParachainClient
    CumulusR[Cumulus Runtime Libraries] -.-> ParachainRuntime
