[package]
name = "pallet-revive-precompile-vesting"
version = "0.1.0"
authors.workspace = true
edition = "2024"
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Vesting precompile for pallet-revive."

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
alloy-core = { workspace = true, features = ["sol-types"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-revive = { workspace = true }
pallet-revive-uapi = { workspace = true, features = ["precompiles-sol-interfaces"] }
pallet-vesting = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-revive/std",
	"pallet-vesting/std",
	"sp-runtime/std",
	"alloy-core/std"
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-revive/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-revive/try-runtime",
	"pallet-vesting/try-runtime",
	"sp-runtime/try-runtime",
]
