[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
args = ["--network-backend=libp2p", "-lparachain=trace", "--rpc-max-response-size=50"]

[[relaychain.nodes]]
name = "bob"
validator = true
args = ["--network-backend=libp2p", "-lparachain=trace", "--rpc-max-response-size=50"]

[[parachains]]
id = 2000
cumulus_based = true
command="polkadot-omni-node"
chain_spec_runtime = { location = "../../target/release/wbuild/battleship-runtime/battleship_runtime.compact.wasm", preset = "local_testnet" }

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-omni-node"
args = ["--network-backend=libp2p", "--ipfs-server", "--force-authoring", "--enable-statement-store", "--authoring=slot-based", "-lparachain=trace,sub-libp2p=trace,sync=trace,statement-gossip=trace,statement-store=trace", "--rpc-max-response-size=50", "--state-pruning=archive"]

[[parachains.collators]]
name = "dave"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-omni-node"
args = ["--network-backend=libp2p", "--ipfs-server", "--enable-statement-store", "-lparachain=trace,sub-libp2p=trace,sync=trace", "--authoring=slot-based", "--state-pruning=archive"]

[[parachains.collators]]
name = "eve"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-omni-node"
args = ["--network-backend=libp2p", "--ipfs-server", "--enable-statement-store", "-lparachain=trace,sub-libp2p=trace,sync=trace", "--authoring=slot-based", "--state-pruning=archive"]
