{
 "title": "Beefy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Beefy Best block",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_beefy_best_block{chain=\"rialto_local\"}"
    },
    {
     "expr": "substrate_beefy_best_block{chain=\"millau_local\"}"
    }
   ]
  },
  {
   "title": "Beefy Lagging Sessions",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_beefy_lagging_sessions{chain=\"rialto_local\"}"
    },
    {
     "expr": "substrate_beefy_lagging_sessions{chain=\"millau_local\"}"
    }
   ]
  },
  {
   "title": "Equivocation votes detected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "substrate_beefy_equivocation_votes"
    }
   ]
  },
  {
   "title": "Invalid votes received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    { "expr": "substrate_beefy_invalid_votes" }
   ]
  },
  {
   "title": "Dropped Buffered Justifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "substrate_beefy_buffered_justifications_dropped"
    }
   ]
  },
  {
   "title": "OnDemand Justifications Engine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "substrate_beefy_on_demand_justification_invalid_proof"
    },
    {
     "expr": "substrate_beefy_on_demand_justification_good_proof"
    },
    {
     "expr": "substrate_beefy_on_demand_justification_peer_error"
    },
    {
     "expr": "beefy_on_demand_justification_peer_refused"
    }
   ]
  },
  {
   "title": "Incoming OnDemand Justifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "substrate_beefy_successful_justification_responses"
    },
    {
     "expr": "substrate_beefy_failed_justification_responses"
    }
   ]
  },
  {
   "title": "Block-import Justifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "substrate_beefy_good_justification_imports"
    },
    {
     "expr": "substrate_beefy_bad_justification_imports"
    }
   ]
  },
  {
   "title": "Buffered Justifications",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "substrate_beefy_buffered_justifications"
    }
   ]
  },
  {
   "title": "Imported Justifications",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "substrate_beefy_imported_justifications"
    }
   ]
  },
  {
   "title": "Stale votes received",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 28 },
   "targets": [
    { "expr": "substrate_beefy_stale_votes" }
   ]
  },
  {
   "title": "Beefy Votes Sent",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_beefy_votes_sent{chain=\"rialto_local\"}"
    },
    {
     "expr": "substrate_beefy_votes_sent{chain=\"millau_local\"}"
    }
   ]
  }
 ]
}