[package]
name = "polkadot-primitives-speculative-messaging"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Primitive types for Polkadot speculative cross-chain messaging"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
serde = { features = ["alloc", "derive"], optional = true, workspace = true }

sp-core = { workspace = true }
sp-runtime = { workspace = true }

polkadot-parachain-primitives = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"polkadot-parachain-primitives/std",
	"scale-info/std",
	"serde?/std",
	"sp-core/std",
	"sp-runtime/std",
]
serde = [
	"dep:serde",
	"scale-info/serde",
	"sp-core/serde",
	"sp-runtime/serde",
]
