name: Command PrDoc

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number
        description: Number of the Pull Request
        required: true
      bump:
        type: choice
        description: Default bump level for all crates
        default: "TODO"
        required: true
        options:
          - "TODO"
          - "none"
          - "patch"
          - "minor"
          - "major"
      audience:
        type: choice
        description: Audience of the PrDoc
        default: "TODO"
        required: true
        options:
          - "TODO"
          - "runtime_dev"
          - "runtime_user"
          - "node_dev"
          - "node_operator"
      overwrite:
        type: boolean
        description: Overwrite existing PrDoc
        default: true
        required: true

concurrency:
  group: command-prdoc
  cancel-in-progress: true

jobs:
  preflight:
    uses: ./.github/workflows/reusable-preflight.yml

  cmd-prdoc:
    needs: [preflight]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Download repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install gh cli
        id: gh
        uses: ./.github/actions/set-up-gh
        with:
          pr-number: ${{ inputs.pr }}
          GH_TOKEN: ${{ github.token }}
      - name: Generate PrDoc
        env:
          PR: ${{ inputs.pr }}
          BUMP: ${{ inputs.bump }}
          AUDIENCE: ${{ inputs.audience }}
          OVERWRITE: ${{ inputs.overwrite }}
        run: |
          python3 -m pip install -q cargo-workspace PyGithub whatthepatch pyyaml toml

          python3 .github/scripts/generate-prdoc.py --pr "$PR" --bump "$BUMP" --audience "$AUDIENCE" --force "$OVERWRITE"

      - name: Report failure
        if: ${{ failure() }}
        env:
          RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GH_TOKEN: ${{ github.token }}
          PR: ${{ inputs.pr }}
          ACTOR: ${{ github.actor }}
          WORKFLOW: ${{ github.workflow }}
        run: gh pr comment "$PR" --body "<h2>Command failed ❌</h2> Run by @$ACTOR for <code>$WORKFLOW</code> failed. See logs <a href=\"$RUN\">here</a>."
      - name: Push Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Add PrDoc (auto generated)
          branch: ${{ steps.gh.outputs.branch }}
          file_pattern: "prdoc/*.prdoc"
