name: Claim Crates

on:
  push:
    branches:
      - master

jobs:
  claim-crates:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Rust Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: install parity-publish
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev pkg-config
          cargo install parity-publish@0.10.17 --locked -q

      - name: parity-publish claim
        env:
          PARITY_PUBLISH_CRATESIO_TOKEN: ${{ secrets.CRATESIO_PUBLISH_CLAIM_TOKEN }}
        run: parity-publish --color always claim
